# Generated by Django 2.1 on 2018-08-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internnummer', models.CharField(max_length=50)),
                ('registreringsnummer', models.CharField(max_length=8)),
                ('karosseritype', models.CharField(max_length=200)),
                ('chassistype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chassisprodusent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Karoserrifabrikk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Selskap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='buss',
            name='chassisprodusent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Chassisprodusent'),
        ),
        migrations.AddField(
            model_name='buss',
            name='karosserifabrikk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Karoserrifabrikk'),
        ),
        migrations.AddField(
            model_name='buss',
            name='selskap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
    ]
