# Generated by Django 2.1 on 2018-08-16 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buss',
            options={'verbose_name_plural': 'busser'},
        ),
        migrations.AlterModelOptions(
            name='chassisprodusent',
            options={'verbose_name_plural': 'chassisprodusenter'},
        ),
        migrations.AlterModelOptions(
            name='karoserrifabrikk',
            options={'verbose_name_plural': 'karoserrifabrikker'},
        ),
        migrations.AlterModelOptions(
            name='selskap',
            options={'verbose_name_plural': 'selskaper'},
        ),
        migrations.AddField(
            model_name='buss',
            name='eier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='chassisprodusent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Chassisprodusent'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='chassistype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='internnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='karosserifabrikk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Karoserrifabrikk'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='karosseritype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='registreringsnummer',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='selskap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
    ]
