# Generated by Django 2.1 on 2018-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0002_auto_20180816_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='byggeår',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='sted',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
