# Generated by Django 2.1 on 2018-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0003_auto_20180816_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='akselavstand',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='beskrivelse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='lengde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='merknad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='motor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='sitteplasser',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='ståplasser',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='vekt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='ytelse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
