# Generated by Django 2.1 on 2018-08-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0004_auto_20180816_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='kort_beskrivelse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
