# Generated by Django 2.1 on 2018-08-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0005_buss_kort_beskrivelse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilde', models.FileField(upload_to='bilder/<django.db.models.fields.related.ForeignKey>')),
                ('buss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Buss')),
            ],
            options={
                'verbose_name_plural': 'bilder',
            },
        ),
    ]
