# Generated by Django 2.1 on 2018-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0008_buss_tilstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilde',
            name='synlig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bilde',
            name='toppbilde',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='opprinnelig_registreringsnummer',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='internnummer',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='bilde',
            unique_together={('buss', 'toppbilde')},
        ),
    ]
