# Generated by Django 2.1 on 2018-08-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0009_auto_20180817_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='understellsnummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bilde',
            name='toppbilde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bilde',
            unique_together=set(),
        ),
    ]
