# Generated by Django 2.1 on 2018-08-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0010_auto_20180817_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='bilde',
            field=models.FileField(upload_to='media/bussbilder/'),
        ),
    ]
