# Generated by Django 2.1 on 2018-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0011_auto_20180817_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buss',
            old_name='kort_beskrivelse',
            new_name='tittel',
        ),
        migrations.AlterField(
            model_name='bilde',
            name='bilde',
            field=models.ImageField(upload_to='media/bussbilder/'),
        ),
    ]
