# Generated by Django 2.1 on 2018-08-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussdatabase', '0012_auto_20180818_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buss',
            name='endret_av',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Endret_av', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buss',
            name='lagt_til',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buss',
            name='lagt_til_av',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Lagt_til_av', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
