# Generated by Django 2.1 on 2018-08-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0013_auto_20180818_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buss',
            name='registreringsnummer',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='vekt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
