# Generated by Django 2.1 on 2018-08-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0015_auto_20180822_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilde',
            old_name='kreditering',
            new_name='fotograf',
        ),
    ]
