# Generated by Django 2.1 on 2018-08-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0019_selskap_forkortelse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buss',
            name='lengde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bussens lengde i meter', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='vekt',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Bussens egenvekt i kg', max_digits=8, null=True),
        ),
    ]
