# Generated by Django 2.1 on 2018-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0020_auto_20180827_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='bredde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bussens bredde i meter', max_digits=4, null=True),
        ),
    ]
