# Generated by Django 2.1 on 2018-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0021_buss_bredde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buss',
            name='vekt',
            field=models.IntegerField(blank=True, help_text='Bussens egenvekt i kg', null=True),
        ),
    ]
