# Generated by Django 2.1.1 on 2018-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0022_auto_20180827_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='buss',
            name='byggnummer',
            field=models.CharField(blank=True, help_text='Karosseriets byggnummer', max_length=200, null=True),
        ),
    ]
