# Generated by Django 2.1.1 on 2018-09-30 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0023_buss_byggnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selskap',
            name='se_også',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='merknad',
            field=models.TextField(blank=True, help_text='Hvis det mangler korrekt valgmulighet for noe kan informasjonen oppgis her', null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='tittel',
            field=models.CharField(blank=True, help_text='Kort tittel eller slagord for busen', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='ytelse',
            field=models.CharField(blank=True, help_text='Ytelse i Hk', max_length=200, null=True),
        ),
    ]
