# Generated by Django 2.1.1 on 2018-10-06 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussdatabase', '0024_auto_20180930_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chassisprodusent',
            options={'ordering': ['navn'], 'verbose_name_plural': 'chassisprodusenter'},
        ),
        migrations.AlterModelOptions(
            name='karoserrifabrikk',
            options={'ordering': ['navn'], 'verbose_name_plural': 'karoserrifabrikker'},
        ),
        migrations.AddField(
            model_name='bilde',
            name='endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bilde',
            name='endret_av',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bilde_endret_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bilde',
            name='lagt_til',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilde',
            name='lagt_til_av',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bilde_lagt_til_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buss',
            name='beskrivelse',
            field=models.TextField(blank=True, help_text='Fortell om bussen og dens historie', null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='endret_av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Endret_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buss',
            name='lagt_til_av',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Lagt_til_av', to=settings.AUTH_USER_MODEL),
        ),
    ]
