# Generated by Django 2.1.1 on 2018-10-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0025_auto_20181006_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='endret',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bilde',
            name='lagt_til',
            field=models.DateTimeField(),
        ),
    ]
