# Generated by Django 2.1.1 on 2018-10-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0026_auto_20181006_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bilde',
            name='lagt_til',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='chassisprodusent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Chassisprodusent'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='karosserifabrikk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Karoserrifabrikk'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='merknad',
            field=models.TextField(blank=True, help_text='Hvis det mangler korrekt valgmulighet                          for noe kan informasjonen oppgis her', null=True),
        ),
        migrations.AlterField(
            model_name='buss',
            name='selskap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Status'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='tilstand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Tilstand'),
        ),
        migrations.AlterField(
            model_name='selskap',
            name='se_også',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
    ]
