# Generated by Django 2.1.1 on 2018-10-26 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussdatabase', '0027_auto_20181026_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selskap',
            old_name='se_også',
            new_name='Se også',
        ),
        migrations.AddField(
            model_name='selskap',
            name='endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='selskap',
            name='endret_av',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Selskap_Endret_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selskap',
            name='lagt_til',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selskap',
            name='lagt_til_av',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Selskap_Lagt_til_av', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selskap',
            name='wikipedia',
            field=models.URLField(blank=True, help_text='Link til wikipediaartikkel om selskapet', null=True),
        ),
    ]
