# Generated by Django 2.1.1 on 2018-10-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0029_auto_20181026_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='selskap',
            name='sted',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='selskap',
            name='Se også',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Selskap'),
        ),
    ]
