# Generated by Django 2.1.1 on 2018-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0030_auto_20181026_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selskap',
            name='Se også',
        ),
        migrations.AddField(
            model_name='selskap',
            name='Se også',
            field=models.ManyToManyField(blank=True, db_table='selskap_related', related_name='_selskap_Se også_+', to='bussdatabase.Selskap'),
        ),
    ]
