# Generated by Django 2.1.1 on 2018-10-27 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0032_auto_20181026_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selskap',
            options={'ordering': ['navn'], 'verbose_name_plural': 'selskaper'},
        ),
        migrations.AlterField(
            model_name='karoserrifabrikk',
            name='navn',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='selskap',
            name='endret_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Selskap_Endret_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='selskap',
            name='navn',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
