# Generated by Django 2.1.2 on 2018-10-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0033_auto_20181027_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='selskap',
            name='navn2',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Alternativt navn'),
        ),
    ]
