# Generated by Django 2.1.1 on 2018-10-27 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussdatabase', '0034_selskap_navn2'),
    ]

    operations = [
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='endret',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='endret_av',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Karoserrifabrikk_Endret_av', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='lagt_til',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='lagt_til_av',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Karoserrifabrikk_Lagt_til_av', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karoserrifabrikk',
            name='se_ogsa',
            field=models.ManyToManyField(blank=True, related_name='_karoserrifabrikk_se_ogsa_+', to='bussdatabase.Karoserrifabrikk', verbose_name='Se også'),
        ),
    ]
