# Generated by Django 2.1.4 on 2019-03-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussdatabase', '0037_auto_20181027_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buss',
            options={'ordering': ['byggeår'], 'verbose_name_plural': 'busser'},
        ),
        migrations.AlterField(
            model_name='buss',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Status'),
        ),
        migrations.AlterField(
            model_name='buss',
            name='tilstand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bussdatabase.Tilstand'),
        ),
        migrations.AlterField(
            model_name='chassisprodusent',
            name='se_ogsa',
            field=models.ManyToManyField(blank=True, help_text='Hold inne ctrl for å velge flere', related_name='_chassisprodusent_se_ogsa_+', to='bussdatabase.Chassisprodusent', verbose_name='Se også'),
        ),
    ]
