# Generated by Django 3.1.5 on 2021-03-14 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussdatabase', '0038_auto_20190309_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('sted', models.CharField(max_length=100)),
                ('nettside', models.URLField()),
                ('beskrivelse', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='foreningslogoer/')),
                ('leder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'foreninger',
            },
        ),
        migrations.AddField(
            model_name='buss',
            name='forening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='busser', to='bussdatabase.forening'),
        ),
    ]
